### PR TITLE
Add Linux compatibility for setup script

### PR DESCRIPTION
**Pull request by vishwamartur**
Related to #8

Add Linux compatibility for setup script.

* **setup.sh**: Create a new `setup.sh` script to install required libraries on Linux. Check if `requirements.txt` exists, exit if not found. Read `requirements.txt` and install each module using `pip`. Print success message after all modules are installed.
* **README.md**: Add instructions for running `setup.sh` on Linux. Mention Linux compatibility in the supported platforms section.

### CODE REVIEW

**Comment by Schuh1337** [comment]
Does the actual tool (schuh.py) even work on Linux?
I didn't have any test grounds as I don't use Linux, and I'm unfamiliar with it.

**Comment by vishwamartur** [comment]
for linux you can use GitHub code space to check
And you can implement CI/CD GitHub workflow

**Comment by Schuh1337** [comment]
I don't think it would work, as one of the first functions declared is one to mess with window's terminal, so I suppose that would just error out on startup on Linux. Also some other internal stuff depends on windows.

**Comment by Schuh1337** [comment]
Thank you for your effort, but I don't think its quite ready.

**Pull request closed without merging**
